from . import help
from . import suralar
from . import start
from . import uzbek
from .API import nomoz_vaqtlari, fotiha_audio, fotiha_api
from . import namoz_vaqtlaari
from .erkaklar_namozi import peshin
from . import viloyat
from . import ortga
from . import namoz
from . import erkaklar_namozi
from . import postlar
from . import command_suralar
from . import dasturchi
from . import malumot
from . import ayollar_namozi
from .ayollar_namozi import bomdod,peshin,asr,shom,xufton
from . import suralar_arab
from . import sura
from . import poklanish
from . import echo