from . import an_nos
from . import ayol_asr
from . import ayol_bomdod
from . import ayol_peshin
from . import ayol_shom
from . import ayol_xufton
from . import erkak_asr
from . import erkak_asr_umumiy
from . import post_inline
from . import erkak_bomdod
from . import erkak_peshin_namozi
from . import erkak_shom_namozi
from . import erkak_xufton_namozi
from . import falaq_sura
from . import fotiha_sura
from . import ixlos_sura
from . import kavsar_sura
from . import namoz
from . import poklanish
from . import poklanish_inline
from . import quron
from . import viloyatlar
