from . import asosiy_button
from . import ayol_bomdod
from . import bomdod
from . import namoz
from . import namoz_default
from . import poklanish
from . import quron
from . import suralar
from . import suralar_arab
